name: untitled2
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  flutter_signature_pad: ^3.0.1
  signature: ^5.4.0
  pdf: ^3.10.4
  path_provider: ^2.0.15
  open_file: ^3.3.2
  flutter_spinkit: ^5.2.0
  printing: ^5.11.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo_Governo.png
    - assets/images/Logo_Sead.png
    - assets/images/Icon_App.png
    - assets/images/Sead_inf.png
    - assets/images/Sead_Sup.png
    - assets/images/car.png
    - assets/images/DGFC.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/DGFC.png"
  web:
    generate: true
    image_path: "assets/images/DGFC.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/DGFC.png"
  macos:
    generate: true
    image_path: "assets/images/DGFC.png"